In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("student_performance.csv")

df.head()

,Student_ID,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass
0,STU001,Joy Ibekwe,Male,23,Computer Science,100.0,4.4,45,44.0,42,43.0,No
1,STU002,Sarah Olatunji,Male,22,AI Engineering,97.0,8.5,57,51.0,53,53.4,Yes
2,STU003,Mariam Abdullahi,Female,20,Data Science,94.0,8.5,71,71.0,61,65.0,Yes
3,STU004,Hannah Uche,Female,24,Data Science,69.0,5.8,54,49.0,46,48.2,No
4,STU005,Daniel Ogunbiyi,Male,22,Data Science,98.0,6.4,48,54.0,55,53.4,Yes

In [4]:
df.isnull().sum()

Student_ID          0
Name                0
Gender              0
Age                 0
Department          0
Attendance          5
Study_Hours         3
Assignment_Score    0
Quiz_Score          3
Exam_Score          0
Final_Score         0
Pass                0
dtype: int64

In [5]:
df["Attendance"] = df["Attendance"].fillna(df["Attendance"].mean())

df["Study_Hours"] = df["Study_Hours"].fillna(df["Study_Hours"].mean())

df["Quiz_Score"] = df["Quiz_Score"].fillna(df["Quiz_Score"].mean())

In [6]:
df.isnull().sum()

Student_ID          0
Name                0
Gender              0
Age                 0
Department          0
Attendance          0
Study_Hours         0
Assignment_Score    0
Quiz_Score          0
Exam_Score          0
Final_Score         0
Pass                0
dtype: int64

In [7]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
97     False
98     False
99     False
100     True
101     True
Length: 102, dtype: bool

In [8]:
df.duplicated().sum()

np.int64(2)

In [9]:
df = df.drop_duplicates()

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler = MinMaxScaler()

df["Study_Hours_Normalized"] = scaler.fit_transform(df[["Study_Hours"]])

df.head()

,Student_ID,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass,Study_Hours_Normalized
0,STU001,Joy Ibekwe,Male,23,Computer Science,100.0,4.4,45,44.0,42,43.0,No,0.041199
1,STU002,Sarah Olatunji,Male,22,AI Engineering,97.0,8.5,57,51.0,53,53.4,Yes,0.194757
2,STU003,Mariam Abdullahi,Female,20,Data Science,94.0,8.5,71,71.0,61,65.0,Yes,0.194757
3,STU004,Hannah Uche,Female,24,Data Science,69.0,5.8,54,49.0,46,48.2,No,0.093633
4,STU005,Daniel Ogunbiyi,Male,22,Data Science,98.0,6.4,48,54.0,55,53.4,Yes,0.116105

In [13]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Gender_Encoded"] = encoder.fit_transform(df["Gender"])

df.head()

,Student_ID,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass,Study_Hours_Normalized,Gender_Encoded
0,STU001,Joy Ibekwe,Male,23,Computer Science,100.0,4.4,45,44.0,42,43.0,No,0.041199,1
1,STU002,Sarah Olatunji,Male,22,AI Engineering,97.0,8.5,57,51.0,53,53.4,Yes,0.194757,1
2,STU003,Mariam Abdullahi,Female,20,Data Science,94.0,8.5,71,71.0,61,65.0,Yes,0.194757,0
3,STU004,Hannah Uche,Female,24,Data Science,69.0,5.8,54,49.0,46,48.2,No,0.093633,0
4,STU005,Daniel Ogunbiyi,Male,22,Data Science,98.0,6.4,48,54.0,55,53.4,Yes,0.116105,1

In [14]:
scaler = MinMaxScaler()

df["Attendance_Normalized"] = scaler.fit_transform(df[["Attendance"]])

df.head()

,Student_ID,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass,Study_Hours_Normalized,Gender_Encoded,Attendance_Normalized
0,STU001,Joy Ibekwe,Male,23,Computer Science,100.0,4.4,45,44.0,42,43.0,No,0.041199,1,1.000000
1,STU002,Sarah Olatunji,Male,22,AI Engineering,97.0,8.5,57,51.0,53,53.4,Yes,0.194757,1,0.960000
2,STU003,Mariam Abdullahi,Female,20,Data Science,94.0,8.5,71,71.0,61,65.0,Yes,0.194757,0,0.920000
3,STU004,Hannah Uche,Female,24,Data Science,69.0,5.8,54,49.0,46,48.2,No,0.093633,0,0.586667
4,STU005,Daniel Ogunbiyi,Male,22,Data Science,98.0,6.4,48,54.0,55,53.4,Yes,0.116105,1,0.973333

In [15]:
df.head()

,Student_ID,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass,Study_Hours_Normalized,Gender_Encoded,Attendance_Normalized
0,STU001,Joy Ibekwe,Male,23,Computer Science,100.0,4.4,45,44.0,42,43.0,No,0.041199,1,1.000000
1,STU002,Sarah Olatunji,Male,22,AI Engineering,97.0,8.5,57,51.0,53,53.4,Yes,0.194757,1,0.960000
2,STU003,Mariam Abdullahi,Female,20,Data Science,94.0,8.5,71,71.0,61,65.0,Yes,0.194757,0,0.920000
3,STU004,Hannah Uche,Female,24,Data Science,69.0,5.8,54,49.0,46,48.2,No,0.093633,0,0.586667
4,STU005,Daniel Ogunbiyi,Male,22,Data Science,98.0,6.4,48,54.0,55,53.4,Yes,0.116105,1,0.973333

In [18]:
df.to_csv("student_performance_cleanedd.csv", index=False)